title: "Dr. Matt Ryan, PhD"
description: "Cybersecurity Specialist & Threat Researcher"
baseurl: ""  
url: "https://cti-buddy.github.io"

sass:
  sass_dir: _sass


plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Add this section to enforce layouts globally
defaults:
  - scope:
      path: ""           # Applies to all files
    values:
      layout: default    # Uses _layouts/default.html

header_pages:
  - about
  - blog

footer_pages:
  - about
  - blog

google_analytics: G-7FF6SF2HED

social_links:
  github: "yourhandle"
  bluesky: "yourhandle"
  mastodon: "yourhandle"
  medium: "yourhandle"
  scholar: "yourhandle"
  linkedin: "yourhandle"
